### ISSUE TITLE
Improve persistent admin notices.

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#46]
- For cleaner adding of new notices with less code.
- To add admin notices that can save forever or specific number of days.
- Don't want to leave options in DB forever until uninstall.
- Use transients instead of options?
- Use built-in dismissable icon.
- Also keep "Dismiss Notice" text link or remove?
- Try implementing https://github.com/collizo4sky/persist-admin-notices-dismissal ?
- Replace or rewrite https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/blob/dev/includes/core/admin/notices.php

**Comment by pderksen** [comment]
Not sure if this is still relevant and/or applies to both Lite & Pro.

**Comment by spencerfinnell** [comment]
Moving to internal discussion in the Pro repository.
