### ISSUE TITLE
Add various site-wide (global) filter hooks that apply to all forms.

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#53]
Such as item description.

Similar to all the values that are filterable in form-specific filters but for all payment forms.

https://github.com/moonstonemedia/WP-Simple-Pay-Snippet-Library/blob/master/form-specific-filters.php

Requested at https://wordpress.org/support/topic/simpay_form_x_y-filter-global-version/

**Comment by pderksen** [comment]
Not sure if this is still relevant and/or applies to both Lite & Pro.

**Comment by spencerfinnell** [comment]
Moved to Pro repository for further discussion. Any updates made will be applied to Lite as well.
