### ISSUE TITLE
Update to Stripe PHP API 7.x / Drop support for PHP 5.4 & 5.5

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#56]
_Do in parallel with Pro version._

- [x] In a minor release leading up to a release with this, check for PHP < 5.6 and add non-dismissable admin notice. #58
- [ ] In this release itself, gracefully halt plugin and show admin notice.

**Comment by drzraf** [comment]
- There is no 7.x release : https://packagist.org/packages/stripe/stripe-php
- stripe-php 6.x supports PHP >= 5.4.0.
- WP 5.0 supports PHP >= 5.2.4
- => Unless `wp-simplepay` itself uses > 5.4 there is no reason to higher version requirements.

**Comment by pderksen** [comment]
@drzraf You're correct in that it's not in master yet, but it will be most likely a part of the 7.x release when that becomes current. https://github.com/stripe/stripe-php/tree/integration-v7

**Comment by spencerfinnell** [comment]
A notice to upgrade to PHP 5.6 will be shown in version 2.1. Once the Stripe PHP API library is updated to 7.x the plugin will require that as a minimum to function: https://github.com/wpsimplepay/WP-Simple-Pay-Lite-for-Stripe/issues/71
