### ISSUE TITLE
Pass $form_id param for non-specific form filters

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#57]
_Done in Pro version._

Sometimes we want to fire a form filter function for all forms instead of specific ones.

[For reference, form-specific filters are called like this.](https://github.com/wpsimplepay/WP-Simple-Pay-Snippet-Library/blob/master/change-api-keys.php)

In some cases users want to detect the form ID inside the function like the example below.

```
function simpay_custom_publishable_key_all_forms( $key, $form_id ) {

	if ( simpay_is_test_mode() ) {

		// Test mode

		switch ( $form_id ) {

			case 146:
				$key = 'pk_test_111111';
				break;

			case 147:
				$key = 'pk_test_222222';
				break;

			case 148:
				$key = 'pk_test_333333';
				break;

			default:
				// Fall back to key saved in settings.
		}

	} else {

		// Live mode

		switch ( $form_id ) {

			case 146:
				$key = 'pk_live_111111';
				break;

			case 147:
				$key = 'pk_live_222222';
				break;

			case 148:
				$key = 'pk_live_333333';
				break;

			default:
				// Fall back to key saved in settings.
		}
	}

	return $key;
}

add_filter( 'simpay_publishable_key', 'simpay_custom_publishable_key_all_forms', 10, 2 );
```

**Comment by spencerfinnell** [comment]
@pderksen Anything left here that isn't covered in https://github.com/wpsimplepay/WP-Simple-Pay-Lite-for-Stripe/pull/68

The shared code snippet works for me in that branch.

**Comment by pderksen** [comment]
Think that was it.
