### ISSUE TITLE
Improve submission handlers (pro)

### ISSUE THREAD

**Issue by drzraf** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#61]
In order to make form processing (much) more flexible, the following changes would be highly appreciated:
- don't rely so much on anonymous or runtime defined functions. Defines objects soon so they can be overriden if needed.
- Add a trigger after `setupStripeElementsForm` (itself run on `simpayBindCoreFormEventsAndTriggers`) which is the only way to touch initialized handlers before they are fired.
- Add a trigger before `handleStripeElementsToken` actually submit, so that custom submission mechanism can be used.

**Comment by spencerfinnell** [comment]
Thank you for the suggestion @drzraf. In the future we hope to refactor some of the Javascript and use some of the more modern JS libraries included in WordPress now, such as Javascript Hooks and Filters: https://github.com/WordPress/gutenberg/tree/master/packages/hooks

I'll add these suggestions to the Pro repository to keep in mind during updates to that code.
