### ISSUE TITLE
Authorize with Stripe Connect

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#65]
All new installs should authorize with Stripe using Connect and _only_ Connect.

Pro version of implementation:
https://github.com/wpsimplepay/WP-Simple-Pay-Pro-3/issues/525

Upgraded users may still be connected via manually entered API keys _until_ they re-authorize with Stripe.

Switching back to manually entered keys will not be doable like it is in Pro.

**Comment by pippinsplugins** [comment]
To help distinguish between Lite and Pro accounts, let's adjust the platform parameter passed in the Stripe API calls.

**Comment by spencerfinnell** [comment]
@pippinsplugins The calls use the plugin name constant, which are currently `WP Simple Pay Pro 3` and `WP Simple Pay` 

Maybe reverse them and include Lite for these calls? Or would that mess up existing logs?

**Comment by pderksen** [comment]
How about leave it at `WP Simple Pay Pro 3` & change Lite to `WP Simple Pay Lite` ?

I suppose the `3` doesn't have to be there anymore for Pro but that was to distinguish folks still using Pro v2 since 3 was a re-write and we supported folks using v2 for quite a while (and some probably still are).

**Comment by pippinsplugins** [comment]
I didn't realize they were already different.

I would vote for `WP Simple Pay Lite` and `WP Simple Pay Pro` just to be more clear. The `3` is irrelevant I think.

**Comment by spencerfinnell** [comment]
> Upgraded users may still be connected via manually entered API keys until they re-authorize with Stripe.

@pippinsplugins @pderksen Should there be a notice/warning before they are redirected to the connection screen about this?

**Comment by pderksen** [comment]
My vote is to leave the notice/warning out for the 2.1.0 release and see if folks complain. :)

**Comment by pippinsplugins** [comment]
I second @pderksen. No need for a notice.
