### ISSUE TITLE
Readme.txt updates for 2.1.0

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#66]
- [x] Update requires/tested/stable tags
- [x] Contributors - Add yourself @spencerfinnell !
- [x] Update features & misc copy throughout @pderksen

**Comment by spencerfinnell** [comment]
@pderksen Added some changelog entries. Kept it basic but there may be more you want to add that were included in the code sync.

**Comment by pderksen** [comment]
@spencerfinnell Think I got the rest of the changelog entries updated that happened with the sync to Pro.
