### ISSUE TITLE
Deprecate Lite 1.x functionality (admin notice only)

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#72]
In June 2017, we launched rewrites of both Lite and Pro to use custom post types. Before that they were purely shortcode based.

For Pro, this meant a brand new version (3.0). For Lite, we bumped the version to 2.0 but kept the 1.x "legacy" settings available.

In June 2018, we ended support for Pro 2.x. In Lite, now that we're in March 2019, I'm thinking it's nearing time to remove the 1.x settings.

In case some Lite users are still using the old shortcodes and settings, let's discuss how we'll warn and phase it out over the next few releases.

I'm thinking similar to how we'll be phasing out old versions of PHP: first #58 then #71. ~~Break this out into two issues as well if it makes sense.~~

See #75 for actual removal of 1.x code.

Not sure if it matters, but 1.x used the `[stripe]` shortcode while 2.x uses `[simpay]`.

**Comment by spencerfinnell** [comment]
For the 2.1.0 release we will show a notice prompting users to migrate their `[stripe]` shortcodes to `[simpay]` if useres DO have a legacy API key but do NOT have a 2.x key (or Stripe Connect auth).
