### ISSUE TITLE
Remove all Lite 1.x settings & references

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/WP-Simple-Pay-Lite-for-Stripe#75]
Continuation of #72.

Bump milestones if needed to release in May 2019 at the earliest.

**Comment by spencerfinnell** [comment]
@pderksen Think it's been long enough to include this in a 2.1.2 (or bump to 2.2.0 release?)

**Comment by pderksen** [comment]
Agreed. 2.1.2 is fine.
